#!/bin/bash
set -x 

#folder=*.zip
#directory=$(basename $folder .zip)
#if [ ! -d "$directory" ]
#then 
#	unzip $folder
#fi

#directory=$(pwd)
#echo $directory
#count=`ls *.c* | wc -l`

process_submission()
{

pushd "$submission_dir"
directory=$(pwd)
outputDir=${directory}/out 			
mkdir -p ${outputDir}
index_file=$outputDir/index_file

#IFS=$'\n'

if [ $2 == "construct_ind" ]
then
	printf "\n${directory##*/}" >> ${RES_CSV}
	printf ", " >> ${RES_CSV}
	unset INDEX_BUILD_FAIL
	make Indexer || INDEX_BUILD_FAIL=1
	if [[ -n ${INDEX_BUILD_FAIL} ]]; then
		printf "T, " >> ${RES_CSV}
		echo "index build failed"
		return
	else
		if [[ ! -f Indexer ]]; then
			printf "T, " >> ${RES_CSV}
			echo "Indexer file not found"
			return
		else		
			printf "F, " >> ${RES_CSV}		
			timeout 1260 time -f "%e" ./Indexer --input $inputDir --output ${index_file} 2>result_temp
			tr -d '\n\t\r' < result_temp >> ${RES_CSV}
			rm result_temp
			printf ", " >> ${RES_CSV}
        	fi
	fi
elif [ $2 == "run_query" ]
then
	#topicFile=$2
	unset RUN_BUILD_FAIL
	make bm25_run || RUN_BUILD_FAIL=1
	if [[ -n ${RUN_BUILD_FAIL} ]]; then
		printf "T, " >> ${RES_CSV}
		echo "Run build failed"
		return
	else
		if [[ ! -f bm25_run ]]; then
			printf "T, " >> ${RES_CSV}
			echo "bm25_run file not found"
			return
		else		
			printf "F, " >> ${RES_CSV}	
			out=${outputDir}/retrieval_out    #name of the output file in which ranked documents are listed according to trec_eval format
			timeout 1260 time -f "%e" ./bm25_run --input ${index_file} --topic $topicFile --output ${out} 2>result_temp
			tr -d '\n\t\r' < result_temp >> ${RES_CSV}			
			cd $trecDir
			printf ", " >> ${RES_CSV}
			./trec_eval -m ndcg_cut.50 $qrels $out > ../result_temp
			grep "ndcg_cut*" ../result_temp | tail -1 | awk '{ printf $3 }' > ../result_temp2
			tr -d '\n\r\t' < ../result_temp2 >> ${RES_CSV}
			rm ../result_temp*
        	fi
	fi
elif [ $2 == "clear" ]
then
	rm -r out
	rm result*
else
	echo "invalid argument"
	return
fi

popd

}

module load compiler/gcc/7.1.0/compilervars
module load lib/boost/1.64.0/gnu1

trecDir=${PWD}/trec_eval-master
RES_CSV=${PWD}/result.csv
qrels=${PWD}/qrel
topicFile=${PWD}/topics.51-100
inputDir=${PWD}/part_1_2_comb

echo "Submission ID, Index Build error?, Time to Index, Run Build error?, Time to run queries, NDCG50 score" > ${RES_CSV}

for submission_dir in 201*; 
do
  #cd $submission_dir
  process_submission "${submission_dir}" construct_ind
  process_submission "${submission_dir}" run_query  
done

