#!/bin/bash

folder=*.zip
directory=$(basename "$folder" .zip)
unzip $folder
cd $directory
count=`ls *.c* | wc -l`

inputDir=$1
outputDir="./out"
topicFile=$2

if [ $count != 0 ]
then 
	make bm25_constIndex
	./constIndex --input $inputDir --output $outputDir
	make bm25_run
	./bm25 --input $inputDir --topic $topicFile --output $outputDir
	out="./bm25.out"
	cd trec_eval-master
	trec_eval -q -m ndcg_cut $qrels $out
#else
#	ant compile
#	java constIndex --input $inputDir --output $outputDir
#	java bm25 --input $inputDir --topic $topicFile --output $outputDir
fi 

